package com.stu.fitconnect

import android.content.res.Resources
import com.google.gson.Gson
import com.stu.fitconnect.features.sportsclubs.domain.SportsClubsFilters

fun main() {
    val jsonString = "{ \"clubs_filters\": { \"isfavourite\": true, \"facilities\": [ { \"id\": \"parking\", \"name\": \"парковка\", \"iconres\": 123, \"isselected\": false }, { \"id\": \"shower\", \"name\": \"душ\", \"iconres\": 456, \"isselected\": false }, { \"id\": \"drinking_water\", \"name\": \"питьевая вода\", \"iconres\": 789, \"isselected\": false }, { \"id\": \"pet_friendly\", \"name\": \"можно с животными\", \"iconres\": 1011, \"isselected\": false }, { \"id\": \"18_plus\", \"name\": \"18+\", \"iconres\": 1213, \"isselected\": false }, { \"id\": \"16_plus\", \"name\": \"16+\", \"iconres\": 1415, \"isselected\": false }, { \"id\": \"14_plus\", \"name\": \"14+\", \"iconres\": 1617, \"isselected\": false }, { \"id\": \"fitness_bar\", \"name\": \"фитнес-бар\", \"iconres\": 1819, \"isselected\": false }, { \"id\": \"sauna\", \"name\": \"сауна\", \"iconres\": 2021, \"isselected\": false }, { \"id\": \"open_24_hours\", \"name\": \"круглосуточно\", \"iconres\": 2223, \"isselected\": false } ], \"cost\": [1, 2, 3], \"clubscategory\": [ { \"id\": \"running\", \"name\": \"бег\", \"isselected\": true }, { \"id\": \"water_sports\", \"name\": \"водные виды\", \"isselected\": false }, { \"id\": \"martial_arts\", \"name\": \"единоборства\", \"isselected\": false }, { \"id\": \"fitness\", \"name\": \"фитнес\", \"isselected\": false }, { \"id\": \"winter_sports\", \"name\": \"зимние виды\", \"isselected\": false }, { \"id\": \"extreme_sports\", \"name\": \"экстремальные виды\", \"isselected\": false }, { \"id\": \"leisure_and_tourism\", \"name\": \"отдых и туризм\", \"isselected\": false }, { \"id\": \"summer_sports\", \"name\": \"летние виды\", \"isselected\": false }, { \"id\": \"air_sports\", \"name\": \"воздушные виды\", \"isselected\": false }, { \"id\": \"strength_sports\", \"name\": \"силовые виды\", \"isselected\": false }, { \"id\": \"shooting_sports\", \"name\": \"стрелковые виды\", \"isselected\": false }, { \"id\": \"acrobatics\", \"name\": \"акробатика\", \"isselected\": false }, { \"id\": \"equestrian_sports\", \"name\": \"эквитация (конный спорт)\", \"isselected\": false }, { \"id\": \"skiing\", \"name\": \"лыжи\", \"isselected\": false }, { \"id\": \"mountain_sports\", \"name\": \"горные виды\", \"isselected\": false }, { \"id\": \"team_sports\", \"name\": \"командные виды\", \"isselected\": false }, { \"id\": \"individual_sports\", \"name\": \"индивидуальные виды\", \"isselected\": false }, { \"id\": \"sports_dance\", \"name\": \"спортивные танцы\", \"isselected\": false }, { \"id\": \"sports_games\", \"name\": \"спортивные игры\", \"isselected\": false }, { \"id\": \"marathons_and_distances\", \"name\": \"марафоны и дистанции\", \"isselected\" :false } ], \"sorttypes\": [ { \"id\": \"a-z\", \"name\": \"а-я\" }, { \"id\": \"z-a\", \"name\": \"я-а\" }, { \"id\": \"count_of_reviews\", \"name\": \"количество отзывов\" }, { \"id\": \"rating\", \"name\":\"рейтинг\" } ] } }"
    val sportsClubsFilters = Gson().fromJson<SportsClubsFilters>(jsonString, SportsClubsFilters::class.java)
    sportsClubsFilters.clubsCategory
}